// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PetTrack.Infrastructure.Persistence;

#nullable disable

namespace PetTrack.Infrastructure.Migrations
{
    [DbContext(typeof(PetTrackContext))]
    [Migration("20260522214150_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetTrack.Domain.Entities.AdesaoMedicamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ADESAO")
                        .HasDefaultValueSql("SEQ_ADESAO.NEXTVAL");

                    b.Property<DateTime>("DataDose")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_DOSE");

                    b.Property<long>("ID_MEDICAMENTO")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_OBSERVACAO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ST_TOMOU");

                    b.HasKey("Id");

                    b.HasIndex("ID_MEDICAMENTO");

                    b.ToTable("TB_ADESAO_MEDICAMENTO", (string)null);
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.Alerta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ALERTA")
                        .HasDefaultValueSql("SEQ_ALERTA.NEXTVAL");

                    b.Property<DateTime>("DataAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ALERTA")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DS_DESCRICAO");

                    b.Property<long>("ID_PET")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ST_RESOLVIDO");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TP_ALERTA");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("NUMBER(8,2)")
                        .HasColumnName("NR_VALOR_REF");

                    b.HasKey("Id");

                    b.HasIndex("ID_PET");

                    b.ToTable("TB_ALERTA", (string)null);
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.BCSHistorico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_BCS")
                        .HasDefaultValueSql("SEQ_BCS_HIST.NEXTVAL");

                    b.Property<byte?>("Bcs")
                        .HasColumnType("NUMBER(2)")
                        .HasColumnName("NR_BCS");

                    b.Property<DateTime>("DataAnalise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ANALISE")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_FOTO_URL");

                    b.Property<long>("ID_PET")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DS_OBSERVACAO");

                    b.HasKey("Id");

                    b.HasIndex("ID_PET");

                    b.ToTable("TB_BCS_HISTORICO", (string)null);
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.Clinica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA")
                        .HasDefaultValueSql("SEQ_CLINICA.NEXTVAL");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("NVARCHAR2(18)")
                        .HasColumnName("NR_CNPJ");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<string>("Endereco")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("DS_ENDERECO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_CLINICA");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NR_TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("TB_CLINICA_CNPJ_UN");

                    b.ToTable("TB_CLINICA", (string)null);
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.CollarLeitura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_LEITURA")
                        .HasDefaultValueSql("SEQ_COLLAR.NEXTVAL");

                    b.Property<decimal?>("Atividade")
                        .HasColumnType("NUMBER(6,2)")
                        .HasColumnName("NR_ATIVIDADE");

                    b.Property<DateTime>("DataLeitura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_LEITURA")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<long>("ID_PET")
                        .HasColumnType("NUMBER(19)");

                    b.Property<decimal>("Temperatura")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("NR_TEMPERATURA");

                    b.Property<string>("TopicoMqtt")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DS_TOPICO_MQTT");

                    b.HasKey("Id");

                    b.HasIndex("ID_PET");

                    b.ToTable("TB_COLLAR_LEITURA", (string)null);
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.EventoClinico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_EVENTO")
                        .HasDefaultValueSql("SEQ_EVENTO_CLINICO.NEXTVAL");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_EVENTO");

                    b.Property<string>("Diagnostico")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DS_DIAGNOSTICO");

                    b.Property<long>("ID_CLINICA")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("ID_PET")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_OBSERVACAO");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TP_EVENTO");

                    b.HasKey("Id");

                    b.HasIndex("ID_CLINICA");

                    b.HasIndex("ID_PET");

                    b.ToTable("TB_EVENTO_CLINICO", (string)null);
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.Medicamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_MEDICAMENTO")
                        .HasDefaultValueSql("SEQ_MEDICAMENTO.NEXTVAL");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_FIM");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_INICIO");

                    b.Property<string>("Dosagem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DS_DOSAGEM");

                    b.Property<string>("Frequencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DS_FREQUENCIA");

                    b.Property<long>("ID_EVENTO")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_MEDICAMENTO");

                    b.HasKey("Id");

                    b.HasIndex("ID_EVENTO");

                    b.ToTable("TB_MEDICAMENTO", (string)null);
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.Notificacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_NOTIFICACAO")
                        .HasDefaultValueSql("SEQ_NOTIFICACAO.NEXTVAL");

                    b.Property<DateTime>("DataEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ENVIO")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<long>("ID_PET")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("ID_TUTOR")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_MENSAGEM");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ST_LIDA");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TP_NOTIFICACAO");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DS_TITULO");

                    b.HasKey("Id");

                    b.HasIndex("ID_PET");

                    b.HasIndex("ID_TUTOR");

                    b.ToTable("TB_NOTIFICACAO", (string)null);
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.Pet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PET")
                        .HasDefaultValueSql("SEQ_PET.NEXTVAL");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("DS_ESPECIE");

                    b.Property<long>("ID_CLINICA")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("ID_TUTOR")
                        .HasColumnType("NUMBER(19)");

                    b.Property<decimal>("Idade")
                        .HasColumnType("NUMBER(3,1)")
                        .HasColumnName("NR_IDADE_ANOS");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_PET");

                    b.Property<decimal>("Peso")
                        .HasColumnType("NUMBER(6,3)")
                        .HasColumnName("NR_PESO_KG");

                    b.Property<string>("Raca")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DS_RACA");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("DS_SEXO");

                    b.HasKey("Id");

                    b.HasIndex("ID_CLINICA");

                    b.HasIndex("ID_TUTOR");

                    b.ToTable("TB_PET", (string)null);
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.ProtocoloPreventivo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PROTOCOLO")
                        .HasDefaultValueSql("SEQ_PROTOCOLO.NEXTVAL");

                    b.Property<DateTime?>("DateAplicacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_APLICACAO");

                    b.Property<DateTime?>("DateProxima")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_PROXIMA");

                    b.Property<long>("ID_PET")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NM_PROTOCOLO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ST_STATUS");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TP_PROTOCOLO");

                    b.HasKey("Id");

                    b.HasIndex("ID_PET");

                    b.ToTable("TB_PROTOCOLO_PREVENTIVO", (string)null);
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.ScoreHistorico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_SCORE")
                        .HasDefaultValueSql("SEQ_SCORE_HIST.NEXTVAL");

                    b.Property<DateTime>("DataRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_REGISTRO")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<long>("ID_PET")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_OBSERVACAO");

                    b.Property<decimal>("Score")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("NR_SCORE");

                    b.HasKey("Id");

                    b.HasIndex("ID_PET");

                    b.ToTable("TB_SCORE_HISTORICO", (string)null);
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.Tutor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TUTOR")
                        .HasDefaultValueSql("SEQ_TUTOR.NEXTVAL");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<string>("Endereco")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("DS_ENDERECO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_TUTOR");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NR_TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("TB_TUTOR_EMAIL_UN");

                    b.ToTable("TB_TUTOR", (string)null);
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.AdesaoMedicamento", b =>
                {
                    b.HasOne("PetTrack.Domain.Entities.Medicamento", "Medicamento")
                        .WithMany("Adesoes")
                        .HasForeignKey("ID_MEDICAMENTO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.Alerta", b =>
                {
                    b.HasOne("PetTrack.Domain.Entities.Pet", "Pet")
                        .WithMany("Alertas")
                        .HasForeignKey("ID_PET")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.BCSHistorico", b =>
                {
                    b.HasOne("PetTrack.Domain.Entities.Pet", "Pet")
                        .WithMany("BcsHistoricos")
                        .HasForeignKey("ID_PET")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.CollarLeitura", b =>
                {
                    b.HasOne("PetTrack.Domain.Entities.Pet", "Pet")
                        .WithMany("CollarLeituras")
                        .HasForeignKey("ID_PET")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.EventoClinico", b =>
                {
                    b.HasOne("PetTrack.Domain.Entities.Clinica", "Clinica")
                        .WithMany("Eventos")
                        .HasForeignKey("ID_CLINICA")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetTrack.Domain.Entities.Pet", "Pet")
                        .WithMany("Eventos")
                        .HasForeignKey("ID_PET")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinica");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.Medicamento", b =>
                {
                    b.HasOne("PetTrack.Domain.Entities.EventoClinico", "Evento")
                        .WithMany("Medicamentos")
                        .HasForeignKey("ID_EVENTO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.Notificacao", b =>
                {
                    b.HasOne("PetTrack.Domain.Entities.Pet", "Pet")
                        .WithMany("Notificacoes")
                        .HasForeignKey("ID_PET")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetTrack.Domain.Entities.Tutor", "Tutor")
                        .WithMany("Notificacoes")
                        .HasForeignKey("ID_TUTOR")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.Pet", b =>
                {
                    b.HasOne("PetTrack.Domain.Entities.Clinica", "Clinica")
                        .WithMany("Pets")
                        .HasForeignKey("ID_CLINICA")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetTrack.Domain.Entities.Tutor", "Tutor")
                        .WithMany("Pets")
                        .HasForeignKey("ID_TUTOR")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.ProtocoloPreventivo", b =>
                {
                    b.HasOne("PetTrack.Domain.Entities.Pet", "Pet")
                        .WithMany("Protocolos")
                        .HasForeignKey("ID_PET")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.ScoreHistorico", b =>
                {
                    b.HasOne("PetTrack.Domain.Entities.Pet", "Pet")
                        .WithMany("Scores")
                        .HasForeignKey("ID_PET")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.Clinica", b =>
                {
                    b.Navigation("Eventos");

                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.EventoClinico", b =>
                {
                    b.Navigation("Medicamentos");
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.Medicamento", b =>
                {
                    b.Navigation("Adesoes");
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.Pet", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("BcsHistoricos");

                    b.Navigation("CollarLeituras");

                    b.Navigation("Eventos");

                    b.Navigation("Notificacoes");

                    b.Navigation("Protocolos");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("PetTrack.Domain.Entities.Tutor", b =>
                {
                    b.Navigation("Notificacoes");

                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
